name: copilot-analytics-$(Build.BuildId)

trigger: none

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MMOPipelineCommon
      name: "DEFRA/eutd-mmo-fes-pipeline-common"
      endpoint: DEFRA
      type: github
      ref: spike/copilot-analytics

variables:
  - group: COPILOT_ANALYTICS

jobs:
  - template: /templates/copilot-analytics.yaml@MMOPipelineCommon
