name: $(BuildID)

trigger: none

pr: none

# schedules:
#   - cron: "30 6 * * 1-5"
#     displayName: Daily Deploy at 6:30 AM UTC
#     branches:
#       include:
#         - main
#     always: true

parameters:
  - name: deployToDevelopmentEnvironment
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: true
  - name: additionalRepositories
    displayName: Additional repositories that needs reference in the process
    type: object
    default: []

resources:
  repositories:
    - repository: MMOPipelineCommon
      name: "DEFRA/eutd-mmo-fes-pipeline-common"
      endpoint: DEFRA
      type: github
      ref: refs/heads/feature/apps-variables-export 

#refs/heads/main

extends:
  template: /includes/infra-deploy.yaml@MMOPipelineCommon
  parameters:
    deployToDevelopmentEnvironment: ${{ parameters.deployToDevelopmentEnvironment }}
    deployToSecondaryRegion: false
    additionalRepositories: 
      - MMOPipelineCommon
    groupedDeployments:
      - name: Import_LogicApps_Workflows
        timeoutInMinutes: 60
        deployments:
          - name: "Import_Reference_LogicApps_Workflow"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "/scripts/Import-Workflows.ps1"
            scriptArguments: -AppsRG "$(resourceGroupName)" -StorageRG "$(storageAccountRGName)" -AppsName "$(logicappsrefdataName)" -StorageAccountName "$(storageAccountName)"
          - name: "Import_Processor_LogicApps_Workflow"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "/scripts/Import-Workflows.ps1"
            scriptArguments: -AppsRG "$(resourceGroupName)" -StorageRG "$(storageAccountRGName)" -AppsName "$(logicappsprocessorName)" -StorageAccountName "$(storageAccountName)"
          - name: "Import Web Apps Variables" 
            scriptRepo: MMOPipelineCommon
            inlineScript: |
              '$(webAppNames)' | ConvertFrom-Json | ForEach-Object {
                & "$(System.DefaultWorkingDirectory)/MMOPipelineCommon/scripts/Import-Workflows.ps1" -AppsRG "$(resourceGroupName)" -StorageRG "$(storageAccountRGName)" -AppsName $_.Name -StorageAccountName "$(storageAccountName)" -EnvironmentVariablesOnly -ContainerName "apps"
              }
          - name: "Import Function Apps Variables"
            scriptRepo: MMOPipelineCommon
            inlineScript: |
              '$(functionApps)' | ConvertFrom-Json | ForEach-Object {
                & "$(System.DefaultWorkingDirectory)/MMOPipelineCommon/scripts/Import-Workflows.ps1" -AppsRG "$(resourceGroupName)" -StorageRG "$(storageAccountRGName)" -AppsName $_.Name -StorageAccountName "$(storageAccountName)" -EnvironmentVariablesOnly -ContainerName "apps"
              }