name: $(BuildID)

trigger: none

pr: none

schedules:
  - cron: "25 14 * * 1-5"
    displayName: Daily Deploy at 6:30 AM UTC
    branches:
      include:
        - main
    always: true

parameters:
  - name: deployToDevelopmentEnvironment
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: true
  - name: additionalRepositories
    displayName: Additional repositories that needs reference in the process
    type: object
    default: []

resources:
  repositories:
    - repository: MMOPipelineCommon
      name: "DEFRA/eutd-mmo-fes-pipeline-common"
      endpoint: DEFRA
      type: github
      ref: refs/heads/main

extends:
  template: /includes/infra-deploy.yaml@MMOPipelineCommon
  parameters:
    deployToDevelopmentEnvironment: ${{ parameters.deployToDevelopmentEnvironment }}
    deployToSecondaryRegion: false
    additionalRepositories: 
      - MMOPipelineCommon
    groupedDeployments:
      - name: Import_LogicApps_Workflows
        timeoutInMinutes: 60
        deployments:
          - name: "Import_LogicApps_Workflow"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "scripts/Import-app-files.ps1"
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            scriptArguments: -AppsRG '$(resourceGroupName)' -StorageRG '$(storageAccountRGName)' -AppsName '$(logicApps)' -StorageAccountName '$(storageAccountName)' -EnvironmentVariablesOnly $false -ContainerName 'workflows'
          - name: "Import_WebApp_Files"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            path: "scripts/Import-app-files.ps1"
            scriptArguments: -AppsRG '$(resourceGroupName)' -StorageRG '$(storageAccountRGName)' -AppsName '$(webAppNames)' -StorageAccountName '$(storageAccountName)' -EnvironmentVariablesOnly $true -ContainerName 'app-files'
          - name: "Import_FunctionApp_Files"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            path: "scripts/Import-app-files.ps1"
            scriptArguments: -AppsRG '$(resourceGroupName)' -StorageRG '$(storageAccountRGName)' -AppsName '$(functionApps)' -StorageAccountName '$(storageAccountName)' -EnvironmentVariablesOnly $true -ContainerName 'app-files'    
         