name: $(BuildID)

trigger: none

# Schedule configuration
# schedules:
#   - cron: "0 19 * * 1-5"
#     displayName: Daily Delete at 7:00 PM UTC
#     branches:
#       include:
#         - main
#     always: true

parameters:
  - name: deployToDevelopmentEnvironment
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: true
  - name: additionalRepositories
    displayName: Additional repositories that needs reference in the process
    type: object
    default: []
  - name: deployToSecondaryRegion
    type: boolean
    default: false

resources:
  repositories:
    - repository: MMOPipelineCommon
      name: "DEFRA/eutd-mmo-fes-pipeline-common"
      endpoint: DEFRA
      type: github
      ref: refs/heads/feature/pipeline-paths-fix

extends:
  template: /includes/infra-deploy.yaml@MMOPipelineCommon
  parameters:
    deployToDevelopmentEnvironment: ${{ parameters.deployToDevelopmentEnvironment }}
    deployToSecondaryRegion: false
    environments:
      - name: "ssv_snd"
        developmentEnvironment: true
        azureRegions:
          primary: UKSouth
        serviceConnection: AZR-MMO-SSV5
        privateAgentName: DEFRA-COMMON-ubuntu2204-SSV5
        deploymentBranches:
          - "*"
      - name: "ssv_dev"
        azureRegions:
          primary: ${{ iif(eq(parameters.deployToSecondaryRegion, false), 'UKSouth', 'UKWest') }}
        serviceConnection: AZR-MMO-SSV5
        privateAgentName: DEFRA-COMMON-ubuntu2204-SSV5
        developmentEnvironment: ${{ parameters.deployToSecondaryRegion }}
        dependsOn: "Validate"
        deploymentBranches:
          - "*"
      - name: "ssv_tst"
        enableTemplateValidationBeforeDeployment: true
        azureRegions:
          primary: UKSouth
        serviceConnection: AZR-MMO-SSV5
        privateAgentName: DEFRA-COMMON-ubuntu2204-SSV5
        dependsOn: "ssv_snd"
        deploymentBranches:
          - "refs/heads/main"
    additionalRepositories: 
      - MMOPipelineCommon
    groupedDeployments:
      - name: Ephemeral_Delete_Images_And_Roles
        timeoutInMinutes: 60
        deployments:
          - name: "Get_WebApps_Existing_Version"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "scripts/Get-ExistingWebAppVersion.ps1"
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            scriptArguments: -WebAppNames '$(webAppNames)' -ResourceGroupName '$(appEnvWebAppRgName)' -IsSlotsEnabled $$(slotsEnabled)
          - name: "Re-tag_Ephemeral_Image"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "scripts/Set-EphemeralTag.ps1"
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            scriptArguments: -acrName '$(acrName)'
          - name: "Get_functionApps_Existing_Version"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "scripts/Get-ExistingWebAppVersion.ps1"
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            scriptArguments: -WebAppNames '$(functionApps)' -ResourceGroupName '$(appEnvWebAppRgName)' -IsSlotsEnabled $$(slotsEnabled)
          - name: "Re_tag_Ephemeral_Image"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "scripts/Set-EphemeralTag.ps1"
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            scriptArguments: -acrName '$(acrName)'
          - name: "Remove_RoleAssignments"
            scriptRepo: MMOPipelineCommon
            type: script
            scriptType: AzurePowerShell
            path: "scripts/Remove-RoleAssignments.ps1"
            condition: and(succeeded(), eq(variables['ephemeral'], true))
            scriptArguments: -ResourceName '$(acrName)' -ResourceGroupName '$(acrResourceGroup)' -ResourceType 'Microsoft.ContainerRegistry/registries' -RoleDefinitionName 'AcrPull' -AppsResourceGroup '$(appEnvWebAppRgName)'
